### ISSUE TITLE
Vad är det här för nått ens?

### ISSUE THREAD

**Issue by HerrLantz** [addreas/template-secrets#1]

**Comment by addreas** [comment]
En [Kubernetes controller](https://kubernetes.io/docs/concepts/architecture/controller/) som skapar [secrets](https://kubernetes.io/docs/concepts/configuration/secret/) utifrån en "template" av något slag och andra secrets som man vill lägga in i sin template.

**Comment by HerrLantz** [comment]
Wow @addreas
